const categories=[['☽','Aqidah','8 kelas'],['◈','Fiqih','12 kelas'],['♡','Akhlak','7 kelas'],['۞','Al-Qur’an','15 kelas'],['☷','Hadits','9 kelas'],['✦','Sirah Nabi','6 kelas'],['أ','Bahasa Arab','5 kelas'],['⌂','Adab Muslim','10 kelas']];
const courses=[
 {title:'Dasar-Dasar Aqidah',cat:'Aqidah',level:'Pemula',lessons:12,desc:'Mengenal dasar keimanan yang menjadi pondasi seorang Muslim.',icon:'☽',popular:96,new:2},
 {title:'Fiqih Ibadah untuk Pemula',cat:'Fiqih',level:'Pemula',lessons:16,desc:'Panduan ringkas memahami ibadah sehari-hari secara bertahap.',icon:'◈',popular:91,new:1},
 {title:'Belajar Membaca Al-Qur’an',cat:'Al-Qur’an',level:'Pemula',lessons:20,desc:'Awali perjalananmu membaca Al-Qur’an dengan pelafalan yang baik.',icon:'۞',popular:98,new:4},
 {title:'Mengenal Sirah Nabi Muhammad ﷺ',cat:'Sirah Nabi',level:'Pemula',lessons:14,desc:'Teladani perjalanan hidup Rasulullah ﷺ dari masa ke masa.',icon:'✦',popular:89,new:3},
 {title:'Akhlak Seorang Muslim',cat:'Akhlak',level:'Pemula',lessons:10,desc:'Membentuk akhlak mulia dalam hubungan dengan Allah dan sesama.',icon:'♡',popular:94,new:5},
 {title:'Bahasa Arab Dasar',cat:'Bahasa Arab',level:'Pemula',lessons:18,desc:'Kenali kosakata dan struktur dasar untuk memahami teks Islam.',icon:'أ',popular:84,new:6}
];
const testimonials=[['“Materinya rapi dan bahasanya sangat mudah saya ikuti. Saya jadi punya arah untuk mulai belajar dari dasar.”','Rizky Mahendra','Mahasiswa','R'],['“Suka sekali karena bisa belajar pelan-pelan di sela kesibukan. Penjelasannya tidak membuat bingung.”','Aisyah Putri','Ibu rumah tangga','A'],['“Tampilan kelasnya tenang, materinya juga ada rujukannya. Sangat membantu untuk mengulang dasar-dasar.”','Fauzan Arif','Karyawan','F']];
const faqs=[['Apakah website ini gratis?','Ya, materi dasar dalam demo ini dapat diakses gratis. Nantinya beberapa kelas pengayaan dapat memiliki ketentuan tersendiri.'],['Apakah cocok untuk pemula?','Sangat cocok. Setiap kelas mencantumkan tingkat kesulitan dan disusun dari konsep dasar.'],['Bagaimana cara mulai belajar?','Pilih kelas yang menarik, buka detailnya, lalu tekan tombol mulai belajar untuk mengikuti modul pertama.'],['Apakah ada quiz?','Ada. Setelah beberapa materi, kamu dapat mengerjakan quiz singkat untuk menguji pemahaman.'],['Apakah progress belajar tersimpan?','Pada versi demo, progres tersimpan selama halaman ini terbuka. Pada produk lengkap, progres tersimpan di akunmu.'],['Bagaimana memastikan materi memiliki sumber terpercaya?','Setiap materi keagamaan perlu menyertakan rujukan. Untuk isu yang kompleks, konsultasikan pula dengan guru atau ulama kompeten.']];
const $=s=>document.querySelector(s);const grid=$('#courseGrid');
function renderCategories(){ $('#categoryGrid').innerHTML=categories.map(c=>`<button class="category" data-cat="${c[1]}"><div class="category-icon">${c[0]}</div><b>${c[1]}</b><span>${c[2]}</span></button>`).join(''); $('#categoryGrid').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#categoryFilter').value=b.dataset.cat; location.hash='kelas';renderCourses()});}
function renderCourses(){let q=$('#search').value.toLowerCase(),c=$('#categoryFilter').value,l=$('#levelFilter').value,sort=$('#sortFilter').value;let list=courses.filter(x=>(c==='all'||x.cat===c)&&(l==='all'||x.level===l)&&(`${x.title} ${x.cat}`.toLowerCase().includes(q))).sort((a,b)=>sort==='popular'?b.popular-a.popular:a.new-b.new);grid.innerHTML=list.map((x,i)=>`<article class="course"><div class="course-art">${x.icon}<small>${x.cat}</small></div><div class="course-body"><h3>${x.title}</h3><p>${x.desc}</p><div class="course-meta"><span>${x.lessons} materi</span><span><b>●</b> ${x.level}</span></div><button class="learn-btn" data-id="${courses.indexOf(x)}">Pelajari kelas →</button></div></article>`).join('');$('#emptyState').hidden=!!list.length;grid.querySelectorAll('.learn-btn').forEach(b=>b.onclick=()=>openCourse(courses[b.dataset.id]));}
function openCourse(c){$('#modalContent').innerHTML=`<div class="modal-hero"><p class="eyebrow">${c.cat} · ${c.level}</p><h2>${c.title}</h2><p>${c.desc}</p></div><div class="modal-body"><div class="modal-meta"><span>◷ ${c.lessons} materi</span><span>◉ Pemula</span><span>♙ Ust. Ahmad</span></div><h3>Daftar modul</h3>${['Pengantar dan tujuan belajar','Materi dasar','Memahami konsep utama','Contoh penerapan','Evaluasi'].map((m,i)=>`<div class="module"><span>0${i+1}</span><div><b>${m}</b><small>${i===4?'Quiz evaluasi':'Materi pembelajaran'}</small></div></div>`).join('')}<button class="btn" id="beginCourse">Mulai Belajar <span>→</span></button></div>`;$('#courseModal').showModal();$('#beginCourse').onclick=()=>{ $('#courseModal').close();$('#quizModal').showModal();renderQuiz()};}
let quizStep=0,score=0;const questions=[['Manakah yang termasuk rukun Islam?',['Beriman kepada malaikat','Mendirikan salat','Berbuat baik kepada tetangga'],1,'Mendirikan salat merupakan rukun Islam yang kedua.'],['Berapa jumlah rukun iman?',['Lima','Enam','Tujuh'],1,'Rukun iman berjumlah enam, sebagaimana dijelaskan dalam hadits Jibril.']];
function renderQuiz(){let q=questions[quizStep];$('#quizProgress').style.width=`${quizStep/questions.length*100}%`;$('#quizContent').innerHTML=`<p class="eyebrow">PERTANYAAN ${quizStep+1} DARI ${questions.length}</p><div class="quiz-question">${q[0]}</div>${q[1].map((a,i)=>`<button class="answer" data-a="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('')}`;$('#quizContent').querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.a,q));}
function answer(i,q){let good=i===q[2];if(good)score++;$('#quizContent').insertAdjacentHTML('beforeend',`<div class="feedback"><b>${good?'Jawaban benar!':'Belum tepat.'}</b><br>${q[3]}</div><button class="btn" id="nextQuiz">${quizStep+1===questions.length?'Lihat hasil':'Pertanyaan berikutnya'} <span>→</span></button>`);$('#quizContent').querySelectorAll('.answer').forEach(b=>b.disabled=true);$('#nextQuiz').onclick=()=>{quizStep++;if(quizStep===questions.length){$('#quizProgress').style.width='100%';$('#quizContent').innerHTML=`<p class="eyebrow">QUIZ SELESAI</p><div class="quiz-question">Masya Allah, kamu mendapat ${score}/${questions.length}</div><p class="muted">Terus ulangi materi dan bertanya kepada pengajar bila ada hal yang belum jelas.</p><button class="btn" id="doneQuiz">Selesai</button>`;$('#doneQuiz').onclick=()=>{$('#quizModal').close();quizStep=0;score=0}}else renderQuiz()};}
function init(){renderCategories();let select=$('#categoryFilter');categories.forEach(c=>select.insertAdjacentHTML('beforeend',`<option>${c[1]}</option>`));renderCourses();$('#search').oninput=renderCourses;['#categoryFilter','#levelFilter','#sortFilter'].forEach(s=>$(s).onchange=renderCourses);$('#showAll').onclick=()=>{select.value='all';$('#levelFilter').value='all';$('#search').value='';renderCourses()};$('#filterToggle').onclick=()=>$('#filters').classList.toggle('show');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'};$('#menuBtn').onclick=()=>$('#navlinks').classList.toggle('open');document.querySelectorAll('.start-btn').forEach(btn=>btn.onclick=()=>{location.hash='kelas';$('#search').focus()});$('#dashboardBtn').onclick=()=>{$('#dashboard').scrollIntoView({behavior:'smooth'});$('.continue').animate([{transform:'scale(1)'},{transform:'scale(1.025)'},{transform:'scale(1)'}],{duration:550})};$('#closeModal').onclick=()=>$('#courseModal').close();$('#closeQuiz').onclick=()=>$('#quizModal').close();$('#faqList').innerHTML=faqs.map(f=>`<div class="faq-item"><div class="faq-q">${f[0]}<span>+</span></div><div class="faq-a">${f[1]}</div></div>`).join('');$('#faqList').querySelectorAll('.faq-item').forEach(x=>x.querySelector('.faq-q').onclick=()=>x.classList.toggle('open'));let ti=0;function testi(){ $('#testiGrid').innerHTML=[0,1,2].map(n=>{let t=testimonials[(ti+n)%3];return `<article class="testi"><span>★★★★★</span><p>${t[0]}</p><div class="person"><i>${t[3]}</i><div><b>${t[1]}</b><small>${t[2]}</small></div></div></article>`}).join('')}testi();$('#nextTesti').onclick=()=>{ti=(ti+1)%3;testi()};$('#prevTesti').onclick=()=>{ti=(ti+2)%3;testi()}}
init();
