const categories = [{ icon: '✦', name: 'Aqidah' }, { icon: '☪', name: 'Tauhid' }, { icon: '◈', name: 'Fiqih' }, { icon: '♡', name: 'Akhlak' }, { icon: '۞', name: 'Al-Qur’an' }, { icon: '☷', name: 'Hadits' }, { icon: '✧', name: 'Sirah Nabi' }, { icon: 'أ', name: 'Bahasa Arab' }, { icon: '⌂', name: 'Adab Muslim' }];

const makeCourse = (title, cat, icon, desc, modules, readings, quiz) => ({ title, cat, icon, desc, level: 'Pemula', modules, readings, quiz });
const courses = [
  makeCourse('Dasar-Dasar Aqidah', 'Aqidah', '✦', 'Materi demo tentang dasar keimanan seorang Muslim.', ['Pengertian aqidah', 'Kedudukan aqidah', 'Rukun iman', 'Menjaga aqidah'], ['Aqidah adalah keyakinan yang tertanam kuat dalam hati. Ia menjadi dasar seorang Muslim dalam mengenal dan beribadah kepada Allah.', 'Aqidah membimbing cara pandang serta perilaku. Karena itu, pelajarilah dengan dalil yang benar dan bimbingan guru yang kompeten.', 'Rukun iman berjumlah enam: iman kepada Allah, malaikat, kitab-kitab, rasul-rasul, hari akhir, serta qada dan qadar.', 'Menjaga aqidah dilakukan dengan belajar, berdoa memohon keteguhan hati, dan berhati-hati terhadap informasi agama tanpa sumber jelas.'], [{ q: 'Apa makna aqidah secara umum?', a: ['Keyakinan yang mengikat hati', 'Aturan jual beli', 'Sejarah suatu negeri'], correct: 0, note: 'Aqidah adalah keyakinan yang tertanam kuat dalam hati.' }, { q: 'Berapa jumlah rukun iman?', a: ['Lima', 'Enam', 'Tujuh'], correct: 1, note: 'Rukun iman berjumlah enam.' }]),
  makeCourse('Pengenalan Tauhid', 'Tauhid', '☪', 'Materi demo untuk mengenal pengesaan Allah dalam ibadah.', ['Makna tauhid', 'Tauhid rububiyah', 'Tauhid uluhiyah', 'Asma wa sifat'], ['Tauhid berarti mengesakan Allah.', 'Tauhid rububiyah adalah keyakinan bahwa Allah Pencipta dan Pengatur alam.', 'Tauhid uluhiyah menuntun agar ibadah hanya ditujukan kepada Allah.', 'Nama dan sifat Allah dipelajari berdasarkan dalil yang sahih.'], [{ q: 'Tauhid uluhiyah berkaitan dengan…', a: ['Mengesakan Allah dalam ibadah', 'Menghitung zakat', 'Menulis hadits'], correct: 0, note: 'Tauhid uluhiyah menuntut ibadah hanya kepada Allah.' }, { q: 'Tujuan mempelajari tauhid adalah…', a: ['Mengenal dan mengesakan Allah', 'Menghafal nama kota', 'Mempelajari perdagangan'], correct: 0, note: 'Tauhid membimbing seorang Muslim untuk beribadah kepada Allah semata.' }]),
  makeCourse('Fiqih Ibadah untuk Pemula', 'Fiqih', '◈', 'Materi demo tentang tata cara ibadah sehari-hari.', ['Pengantar fiqih ibadah', 'Bersuci', 'Waktu salat', 'Rukun salat'], ['Fiqih ibadah membahas panduan praktis beribadah. Pelajari tahap demi tahap agar penerapannya lebih tertib.', 'Bersuci adalah persiapan penting sebelum ibadah tertentu. Wudu dilakukan dengan air suci untuk menghilangkan hadas kecil.', 'Salat lima waktu memiliki waktu yang telah ditetapkan. Menjaga waktunya adalah bagian dari kedisiplinan ibadah.', 'Rukun salat adalah bagian yang harus dikerjakan agar salat sah. Rincian praktiknya sebaiknya dipelajari bersama pengajar.'], [{ q: 'Bersuci sebelum salat disebut…', a: ['Wudu', 'Puasa', 'I’tikaf'], correct: 0, note: 'Wudu adalah salah satu bentuk bersuci sebelum salat.' }, { q: 'Manakah ibadah wajib harian?', a: ['Salat lima waktu', 'Membaca novel', 'Berolahraga'], correct: 0, note: 'Salat lima waktu merupakan kewajiban bagi Muslim yang memenuhi syarat.' }]),
  makeCourse('Akhlak Seorang Muslim', 'Akhlak', '♡', 'Materi demo tentang membiasakan perilaku terpuji.', ['Pengertian akhlak', 'Jujur', 'Amanah', 'Berbuat baik kepada sesama'], ['Akhlak adalah perilaku yang tampak dalam keseharian. Akhlak baik dibangun melalui ilmu, latihan, dan kebiasaan.', 'Jujur berarti berkata dan bertindak sesuai kenyataan. Sikap ini membangun kepercayaan dalam hubungan dengan orang lain.', 'Amanah berarti menjaga titipan dan menunaikan tanggung jawab. Mulailah dari hal kecil, seperti menepati janji.', 'Berbuat baik kepada sesama dapat dilakukan dengan ucapan lembut, menghormati orang lain, dan memberi pertolongan yang tepat.'], [{ q: 'Contoh sikap amanah adalah…', a: ['Menjaga titipan', 'Mengingkari janji', 'Mengejek teman'], correct: 0, note: 'Amanah berarti dapat dipercaya dalam menjaga titipan dan tanggung jawab.' }, { q: 'Sikap baik ketika berbicara adalah…', a: ['Berkata santun dan benar', 'Memotong pembicaraan', 'Menyebarkan kabar tanpa cek'], correct: 0, note: 'Akhlak baik tercermin dari ucapan yang santun dan benar.' }]),
  makeCourse('Belajar Membaca Al-Qur’an', 'Al-Qur’an', '۞', 'Materi demo pengenalan adab dan tahapan membaca Al-Qur’an.', ['Adab membaca Al-Qur’an', 'Huruf hijaiyah', 'Harakat dasar', 'Latihan pelafalan'], ['Membaca Al-Qur’an dilakukan dengan adab yang baik dan niat mencari petunjuk.', 'Huruf hijaiyah adalah dasar membaca teks Arab.', 'Harakat membantu menentukan bunyi huruf ketika dibaca.', 'Latihan pelafalan dilakukan perlahan dan dapat dibimbing pengajar.'], [{ q: 'Sikap sebelum membaca Al-Qur’an adalah…', a: ['Menjaga adab dan kebersihan', 'Bercanda berlebihan', 'Mengabaikan bacaan'], correct: 0, note: 'Membaca Al-Qur’an dilakukan dengan adab yang baik.' }, { q: 'Huruf hijaiyah digunakan untuk…', a: ['Membaca tulisan Arab', 'Menghitung waktu', 'Menggambar peta'], correct: 0, note: 'Huruf hijaiyah merupakan dasar untuk membaca teks Arab.' }]),
  makeCourse('Pengantar Ilmu Hadits', 'Hadits', '☷', 'Materi demo untuk mengenal hadits sebagai sumber ajaran Islam.', ['Pengertian hadits', 'Unsur hadits', 'Fungsi hadits', 'Adab mempelajari hadits'], ['Hadits adalah riwayat tentang Nabi Muhammad ﷺ.', 'Pengantar hadits mengenalkan pihak yang meriwayatkan dan isi riwayat.', 'Hadits menjelaskan serta melengkapi pemahaman terhadap Al-Qur’an.', 'Pelajari hadits dari sumber yang dapat dipertanggungjawabkan.'], [{ q: 'Hadits berisi riwayat tentang…', a: ['Perkataan, perbuatan, atau persetujuan Nabi', 'Daftar mata uang', 'Nama benua'], correct: 0, note: 'Hadits meriwayatkan perkataan, perbuatan, dan persetujuan Nabi ﷺ.' }, { q: 'Sumber ajaran Islam yang utama adalah…', a: ['Al-Qur’an', 'Cerita rakyat', 'Buku pelajaran umum'], correct: 0, note: 'Al-Qur’an adalah sumber ajaran Islam yang utama.' }]),
  makeCourse('Mengenal Sirah Nabi Muhammad ﷺ', 'Sirah Nabi', '✧', 'Materi demo tentang perjalanan hidup Rasulullah ﷺ.', ['Arti sirah', 'Masa kecil Nabi', 'Dakwah di Makkah', 'Hijrah ke Madinah'], ['Sirah adalah kajian perjalanan hidup Rasulullah ﷺ.', 'Masa kecil Nabi mengajarkan keteladanan dan keteguhan.', 'Dakwah di Makkah berlangsung dengan kesabaran di tengah tantangan.', 'Hijrah ke Madinah menjadi peristiwa penting dalam sejarah Islam.'], [{ q: 'Sirah Nabi mempelajari…', a: ['Perjalanan hidup Rasulullah ﷺ', 'Rumus fisika', 'Jenis tumbuhan'], correct: 0, note: 'Sirah adalah kajian perjalanan hidup Nabi Muhammad ﷺ.' }, { q: 'Kota tujuan hijrah Nabi adalah…', a: ['Madinah', 'Yaman', 'Thaif'], correct: 0, note: 'Nabi Muhammad ﷺ berhijrah dari Makkah ke Madinah.' }]),
  makeCourse('Bahasa Arab Dasar', 'Bahasa Arab', 'أ', 'Materi demo mengenal kosakata dan ungkapan Arab dasar.', ['Salam', 'Kata benda', 'Kata ganti', 'Kosakata harian'], ['Salam adalah ungkapan doa dan penghormatan dalam bahasa Arab.', 'Kata benda digunakan untuk menyebut orang, benda, atau tempat.', 'Kata ganti membantu menyebut orang pertama, kedua, atau ketiga.', 'Kosakata harian sebaiknya diulang dan dipraktikkan sedikit demi sedikit.'], [{ q: 'Arti “kitab” adalah…', a: ['Buku', 'Rumah', 'Pintu'], correct: 0, note: 'Kitab berarti buku.' }, { q: 'Ungkapan salam dalam bahasa Arab adalah…', a: ['Assalamu’alaikum', 'Selamat malam', 'Terima kasih'], correct: 0, note: 'Assalamu’alaikum adalah salam yang lazim digunakan Muslim.' }]),
  makeCourse('Adab Muslim Sehari-hari', 'Adab Muslim', '⌂', 'Materi demo tentang adab di rumah, sekolah, dan masyarakat.', ['Makna adab', 'Adab kepada orang tua', 'Adab berteman', 'Adab makan dan minum'], ['Adab adalah tata perilaku baik yang mencerminkan penghormatan kepada Allah dan sesama.', 'Berbuat baik dan berbicara santun kepada orang tua merupakan adab penting.', 'Dalam berteman, jaga ucapan dan perlakukan teman dengan baik.', 'Makan dan minum dilakukan dengan bersyukur serta tidak berlebihan.'], [{ q: 'Salah satu adab kepada orang tua adalah…', a: ['Berbicara dengan hormat', 'Membentak', 'Mengabaikan nasihat baik'], correct: 0, note: 'Seorang Muslim diperintahkan menghormati dan berbuat baik kepada orang tua.' }, { q: 'Ketika makan, sikap yang baik adalah…', a: ['Mengucap basmalah', 'Mencela makanan', 'Membuang-buang makanan'], correct: 0, note: 'Mengucap basmalah termasuk adab makan.' }])
];
const faqs = [['Apakah website ini gratis?', 'Ini adalah tampilan demo. Ketentuan akses akan ditentukan setelah sistem akun dan database tersedia.'], ['Apakah cocok untuk pemula?', 'Ya. Semua kelas demo diberi tingkat pemula dan disusun sebagai pengantar.'], ['Bagaimana cara mulai belajar?', 'Pilih kategori atau kelas, lalu baca materi dan kerjakan quiz yang sesuai kategorinya.'], ['Apakah ada quiz?', 'Ada quiz demo khusus di setiap kelas; soal Fiqih, Aqidah, Tauhid, Akhlak, dan kategori lain berbeda.'], ['Apakah progres tersimpan?', 'Belum. Tidak ada akun atau database pada versi ini, sehingga progres tidak dicatat.']];
const levelProfiles = [
  { level: 'Dasar', desc: 'Memahami istilah, tujuan, dan urutan konsep utama.', reading: 'Pada tingkat dasar, fokuskan belajar pada istilah penting dan hubungan antarkonsep sebelum melanjutkan praktik.' },
  { level: 'Menengah', desc: 'Menerapkan konsep melalui contoh dan situasi sehari-hari.', reading: 'Pada tingkat menengah, hubungkan konsep ini dengan situasi sehari-hari dan periksa kembali rujukannya.' },
  { level: 'Lanjutan', desc: 'Menganalisis penerapan materi dengan rujukan yang tepat.', reading: 'Pada tingkat lanjutan, bandingkan penerapan materi secara hati-hati dan rujuk guru kompeten untuk rincian yang membutuhkan penjelasan.' }
];
function levelQuiz(course, profile) {
  const [first, second, third, fourth] = course.modules;
  const prompts = profile.level === 'Dasar'
    ? [`Topik pembuka kelas ${course.cat} adalah…`, `Materi setelah “${first}” adalah…`, `Tujuan belajar ${course.cat} pada tingkat dasar adalah…`, `Topik “${third}” termasuk dalam kelas…`, `Sikap tepat saat belum memahami materi adalah…`]
    : profile.level === 'Menengah'
      ? [`Saat mempelajari “${first}”, langkah awal yang tepat adalah…`, `Konsep “${second}” paling baik dipahami melalui…`, `Penerapan materi ${course.cat} perlu disertai…`, `Saat menemukan contoh baru terkait “${third}”, sebaiknya…`, `Untuk menguatkan pemahaman ${course.cat}, pelajar perlu…`]
      : [`Saat menemukan perbedaan penjelasan tentang “${first}”, sikap yang tepat adalah…`, `Penerapan “${second}” pada situasi baru sebaiknya didasarkan pada…`, `Untuk menganalisis “${third}”, pelajar perlu memperhatikan…`, `Pembahasan “${fourth}” yang rumit sebaiknya dikonsultasikan kepada…`, `Kesimpulan belajar ${course.cat} yang baik harus…`];
  const answers = profile.level === 'Dasar'
    ? [[first, 'Topik dari kategori lain', 'Data yang tidak dibahas'], [second, 'Nama kelas lain', 'Topik yang tidak tersedia'], ['Memahami konsep utama', 'Menghafal tanpa memahami', 'Melewati semua materi'], [course.cat, 'Kategori yang tidak dipilih', 'Statistik demo'], ['Membaca ulang dan bertanya pada pengajar', 'Menebak tanpa belajar', 'Mengabaikan materi']]
    : profile.level === 'Menengah'
      ? [['Membaca materi dan memahami tujuannya', 'Langsung mengerjakan tanpa membaca', 'Menggunakan jawaban kategori lain'], ['Contoh yang relevan dan rujukan yang benar', 'Tebakan acak', 'Informasi tanpa sumber'], ['Pemahaman konsep dan bimbingan yang tepat', 'Perbandingan tanpa dasar', 'Jawaban dari kelas lain'], ['Menghubungkannya dengan konsep yang dipelajari', 'Mengabaikan rujukan', 'Mengganti kategorinya'], ['Mengulang materi dan menerapkannya dengan benar', 'Melewati evaluasi', 'Menyalin jawaban']]
      : [['Memeriksa rujukan dan bertanya kepada guru kompeten', 'Memilih pendapat tanpa dasar', 'Menyebarkan tanpa memeriksa'], ['Dalil, konteks, dan bimbingan yang tepat', 'Kebiasaan tanpa ilmu', 'Jawaban dari kategori lain'], ['Tujuan, dalil, dan konteks penerapan', 'Satu contoh saja', 'Pendapat tanpa rujukan'], ['Guru atau ulama yang kompeten', 'Komentar acak', 'Data statistik'], ['Berdasarkan materi dan rujukan yang benar', 'Berdasarkan tebakan', 'Mengikuti jawaban kelas lain']];
  return prompts.map((q, index) => ({ q, a: answers[index], correct: 0, note: `Jawaban ini sesuai tujuan pembelajaran tingkat ${profile.level} untuk kelas ${course.cat}.` }));
}
const originalCourses = [...courses];
originalCourses.forEach(course => levelProfiles.forEach(profile => courses.push({ ...course, title: `${course.title} — ${profile.level}`, level: profile.level, desc: `${course.desc} ${profile.desc}`, readings: course.readings.map(reading => `${reading} ${profile.reading}`), quiz: levelQuiz(course, profile) })));
const extraQuiz = {
  Aqidah: [{ q: 'Aqidah menjadi dasar dalam…', a: ['Keyakinan dan ibadah seorang Muslim', 'Menghitung perdagangan', 'Menentukan arah perjalanan'], correct: 0, note: 'Aqidah menjadi fondasi keyakinan seorang Muslim.' }, { q: 'Sikap terhadap informasi agama tanpa sumber jelas adalah…', a: ['Berhati-hati dan mencari rujukan', 'Langsung menyebarkannya', 'Menganggap semua sama'], correct: 0, note: 'Pelajari agama dari sumber dan pengajar yang dapat dipercaya.' }, { q: 'Salah satu cara menjaga aqidah adalah…', a: ['Berdoa memohon keteguhan hati', 'Mengabaikan ilmu', 'Mengikuti semua kabar'], correct: 0, note: 'Seorang Muslim memohon keteguhan hati kepada Allah.' }],
  Fiqih: [{ q: 'Fiqih ibadah membantu Muslim memahami…', a: ['Panduan praktis beribadah', 'Nama-nama benua', 'Aturan olahraga'], correct: 0, note: 'Fiqih ibadah mempelajari panduan praktis beribadah.' }, { q: 'Wudu dilakukan untuk…', a: ['Bersuci dari hadas kecil', 'Mengganti waktu salat', 'Menentukan arah kiblat'], correct: 0, note: 'Wudu merupakan cara bersuci dari hadas kecil.' }, { q: 'Rukun salat perlu dipelajari karena…', a: ['Menentukan bagian salat yang harus dikerjakan', 'Menggantikan semua ibadah', 'Menghapus waktu salat'], correct: 0, note: 'Rukun salat adalah bagian yang harus dikerjakan agar salat sah.' }],
  Akhlak: [{ q: 'Akhlak baik dibangun melalui…', a: ['Ilmu, latihan, dan kebiasaan', 'Ucapan kasar', 'Menghindari tanggung jawab'], correct: 0, note: 'Akhlak baik perlu dipelajari dan dilatih dalam keseharian.' }, { q: 'Kejujuran membangun…', a: ['Kepercayaan', 'Permusuhan', 'Kesalahpahaman'], correct: 0, note: 'Kejujuran menguatkan kepercayaan dengan orang lain.' }, { q: 'Menepati janji adalah contoh…', a: ['Amanah', 'Kesombongan', 'Kecerobohan'], correct: 0, note: 'Menepati janji termasuk bentuk amanah.' }]
};
courses.forEach(course => {
  const fallback = course.modules.slice(1).map((module, index) => ({ q: `Materi ${index + 2} pada kelas ${course.cat} membahas…`, a: [module, 'Topik dari kelas lain', 'Data yang tidak dibahas'], correct: 0, note: `Materi ini secara khusus membahas ${module}.` }));
  course.quiz.push(...(extraQuiz[course.cat] || fallback).slice(0, Math.max(0, 5 - course.quiz.length)));
});
const $ = selector => document.querySelector(selector);
const competencyQuestions = [
  { q: 'Rukun iman berjumlah…', a: ['Empat', 'Lima', 'Enam', 'Tujuh', 'Delapan'], correct: 2, note: 'Rukun iman berjumlah enam.' },
  { q: 'Bersuci sebelum salat dengan air disebut…', a: ['Puasa', 'Wudu', 'Zakat', 'Haji', 'I’tikaf'], correct: 1, note: 'Wudu adalah salah satu bentuk bersuci sebelum salat.' },
  { q: 'Menjaga titipan merupakan contoh akhlak…', a: ['Amanah', 'Sombong', 'Dengki', 'Boros', 'Marah'], correct: 0, note: 'Amanah berarti dapat dipercaya dalam menjaga titipan dan tanggung jawab.' },
  { q: 'Ibadah hanya ditujukan kepada…', a: ['Diri sendiri', 'Orang tua', 'Allah', 'Teman', 'Malaikat'], correct: 2, note: 'Seorang Muslim beribadah hanya kepada Allah.' },
  { q: 'Sikap baik saat berbicara adalah…', a: ['Memotong pembicaraan', 'Mengejek', 'Berkata santun dan benar', 'Menyebarkan kabar tanpa cek', 'Membentak'], correct: 2, note: 'Akhlak baik tercermin dalam ucapan yang santun dan benar.' }
];
let activeCourse = null, quizStep = 0, score = 0, competencyStep = 0, competencyScore = 0;
function courseCount(category) { return courses.filter(course => course.cat === category).length; }
function renderCategories() { $('#categoryGrid').innerHTML = categories.map(category => `<button class="category" data-cat="${category.name}"><div class="category-icon">${category.icon}</div><b>${category.name}</b><span>${courseCount(category.name)} kelas demo</span></button>`).join(''); $('#categoryGrid').querySelectorAll('.category').forEach(button => button.onclick = () => { $('#categoryFilter').value = button.dataset.cat; location.hash = 'kelas'; renderCourses(); }); }
function renderCourses() { const query = $('#search').value.trim().toLowerCase(), category = $('#categoryFilter').value, level = $('#levelFilter').value; const list = courses.filter(course => (category === 'all' || course.cat === category) && (level === 'all' || course.level === level) && `${course.title} ${course.cat} ${course.desc}`.toLowerCase().includes(query)); $('#courseGrid').innerHTML = list.map(course => `<article class="course"><div class="course-art">${course.icon}<small>${course.cat} · demo</small></div><div class="course-body"><h3>${course.title}</h3><p>${course.desc}</p><div class="course-meta"><span>${course.modules.length} materi demo</span><span><b>●</b> ${course.level}</span></div><button class="learn-btn" data-title="${course.title}">Pelajari kelas →</button></div></article>`).join(''); $('#emptyState').hidden = Boolean(list.length); $('#courseGrid').querySelectorAll('.learn-btn').forEach(button => button.onclick = () => openCourse(courses.find(course => course.title === button.dataset.title))); }
function openLesson(index) {
  $('#courseModal').close();
  $('#lessonContent').style.padding = '28px';
  $('#lessonTitle').textContent = `Materi ${index + 1} · ${activeCourse.cat} · demo`;
  $('#lessonProgress').style.width = `${((index + 1) / activeCourse.modules.length) * 100}%`;
  $('#lessonContent').innerHTML = `<p class="eyebrow">MATERI ${index + 1} DARI ${activeCourse.modules.length}</p><div class="quiz-question">${activeCourse.modules[index]}</div><p class="muted">${activeCourse.readings[index]}</p><div class="hero-buttons"><button class="outline-btn" id="backToCourse">← Kembali ke kelas</button>${index < activeCourse.modules.length - 1 ? `<button class="btn" id="nextLesson">Materi berikutnya <span>→</span></button>` : `<button class="btn" id="lessonQuiz">Mulai quiz ${activeCourse.cat} <span>→</span></button>`}</div>`;
  $('#lessonModal').showModal();
  $('#backToCourse').onclick = () => { $('#lessonModal').close(); openCourse(activeCourse); };
  if (index < activeCourse.modules.length - 1) $('#nextLesson').onclick = () => { $('#lessonModal').close(); openLesson(index + 1); };
  else $('#lessonQuiz').onclick = () => { $('#lessonModal').close(); quizStep = 0; score = 0; $('#quizModal').showModal(); renderQuiz(); };
}
function openCourse(course) { activeCourse = course; $('#modalContent').innerHTML = `<div class="modal-hero"><p class="eyebrow">${course.cat} · ${course.level} · DEMO</p><h2>${course.title}</h2><p>${course.desc}</p></div><div class="modal-body"><div class="modal-meta"><span>◷ ${course.modules.length} materi</span><span>◉ ${course.level}</span><span>Konten demo</span></div><h3>Daftar materi</h3>${course.modules.map((module, index) => `<div class="module"><span>${String(index + 1).padStart(2, '0')}</span><div><b>${module}</b><small>Materi ${course.cat}</small><button class="learn-btn read-lesson" data-lesson="${index}">Baca materi →</button></div></div>`).join('')}<button class="btn" id="beginCourse">Mulai quiz ${course.cat} <span>→</span></button></div>`; $('#modalContent').querySelectorAll('.read-lesson').forEach(button => button.onclick = () => openLesson(Number(button.dataset.lesson))); $('#courseModal').showModal(); $('#beginCourse').onclick = () => { $('#courseModal').close(); quizStep = 0; score = 0; $('#quizModal').showModal(); renderQuiz(); }; }
function renderQuiz() { const question = activeCourse.quiz[quizStep]; $('#quizTitle').textContent = `Quiz · ${activeCourse.cat} · demo`; $('#quizProgress').style.width = `${(quizStep / activeCourse.quiz.length) * 100}%`; $('#quizContent').innerHTML = `<p class="eyebrow">PERTANYAAN ${quizStep + 1} DARI ${activeCourse.quiz.length}</p><div class="quiz-question">${question.q}</div>${question.a.map((answer, index) => `<button class="answer" data-answer="${index}">${String.fromCharCode(65 + index)}. ${answer}</button>`).join('')}`; $('#quizContent').querySelectorAll('.answer').forEach(button => button.onclick = () => answerQuiz(Number(button.dataset.answer), question)); }
function answerQuiz(selected, question) { const correct = selected === question.correct; if (correct) score += 1; $('#quizContent').querySelectorAll('.answer').forEach(button => button.disabled = true); $('#quizContent').insertAdjacentHTML('beforeend', `<div class="feedback"><b>${correct ? 'Jawaban benar.' : 'Belum tepat.'}</b><br>${question.note}</div><button class="btn" id="nextQuiz">${quizStep + 1 === activeCourse.quiz.length ? 'Lihat hasil' : 'Pertanyaan berikutnya'} <span>→</span></button>`); $('#nextQuiz').onclick = () => { quizStep += 1; if (quizStep < activeCourse.quiz.length) return renderQuiz(); const finalScore = Math.round((score / activeCourse.quiz.length) * 100); $('#quizProgress').style.width = '100%'; $('#quizContent').innerHTML = `<p class="eyebrow">QUIZ DEMO SELESAI</p><div class="quiz-question">Nilai quiz ${activeCourse.cat}: ${finalScore}</div><p class="muted">Hasil ini tidak disimpan karena database belum tersedia.</p><button class="btn" id="doneQuiz">Selesai</button>`; $('#doneQuiz').onclick = () => $('#quizModal').close(); }; }
function renderCompetencyExam() { const question = competencyQuestions[competencyStep]; $('#competencyProgress').style.width = `${(competencyStep / competencyQuestions.length) * 100}%`; $('#competencyContent').innerHTML = `<p class="eyebrow">PERTANYAAN ${competencyStep + 1} DARI ${competencyQuestions.length}</p><div class="quiz-question">${question.q}</div>${question.a.map((answer, index) => `<button class="answer" data-answer="${index}">${String.fromCharCode(65 + index)}. ${answer}</button>`).join('')}`; $('#competencyContent').querySelectorAll('.answer').forEach(button => button.onclick = () => answerCompetency(Number(button.dataset.answer), question)); }
function answerCompetency(selected, question) { const correct = selected === question.correct; if (correct) competencyScore += 1; $('#competencyContent').querySelectorAll('.answer').forEach(button => button.disabled = true); $('#competencyContent').insertAdjacentHTML('beforeend', `<div class="feedback"><b>${correct ? 'Jawaban benar.' : 'Belum tepat.'}</b><br>${question.note}</div><button class="btn" id="nextCompetency">${competencyStep + 1 === competencyQuestions.length ? 'Lihat hasil' : 'Pertanyaan berikutnya'} <span>→</span></button>`); $('#nextCompetency').onclick = () => { competencyStep += 1; if (competencyStep < competencyQuestions.length) return renderCompetencyExam(); const finalScore = Math.round((competencyScore / competencyQuestions.length) * 100); $('#competencyProgress').style.width = '100%'; $('#competencyContent').innerHTML = `<p class="eyebrow">UJI KOMPETENSI SELESAI</p><div class="quiz-question">Nilai uji kompetensi: ${finalScore}</div><p class="muted">Hasil ini hanya ditampilkan pada perangkat ini dan belum disimpan ke database.</p><button class="btn" id="doneCompetency">Selesai</button>`; $('#doneCompetency').onclick = () => $('#competencyModal').close(); }; }
function openCompetencyExam() { competencyStep = 0; competencyScore = 0; $('#competencyModal').showModal(); renderCompetencyExam(); }
function init() { document.body.insertAdjacentHTML('beforeend', `<dialog id="lessonModal"><button class="close-modal" id="closeLesson" aria-label="Tutup">×</button><div class="quiz-head"><p class="eyebrow" id="lessonTitle">Materi demo</p><h2>Baca materi</h2><div class="progress"><i id="lessonProgress" style="width:0"></i></div></div><div id="lessonContent"></div></dialog>`); renderCategories(); categories.forEach(category => $('#categoryFilter').insertAdjacentHTML('beforeend', `<option value="${category.name}">${category.name}</option>`)); renderCourses(); $('#search').oninput = renderCourses; ['#categoryFilter', '#levelFilter', '#sortFilter'].forEach(selector => $(selector).onchange = renderCourses); $('#showAll').onclick = () => { $('#categoryFilter').value = 'all'; $('#levelFilter').value = 'all'; $('#search').value = ''; renderCourses(); }; $('#filterToggle').onclick = () => $('#filters').classList.toggle('show'); $('#themeBtn').onclick = () => { document.body.classList.toggle('dark'); $('#themeBtn').textContent = document.body.classList.contains('dark') ? '☀' : '☾'; }; $('#menuBtn').onclick = () => $('#navlinks').classList.toggle('open'); $('#navlinks').querySelectorAll('a').forEach(link => link.onclick = () => $('#navlinks').classList.remove('open')); document.querySelectorAll('.start-btn').forEach(button => button.onclick = () => { location.hash = 'kelas'; $('#search').focus(); }); $('#dashboardBtn').onclick = () => { location.hash = 'kelas'; $('#search').focus(); }; $('#closeModal').onclick = () => $('#courseModal').close(); $('#closeQuiz').onclick = () => $('#quizModal').close(); $('#closeLesson').onclick = () => $('#lessonModal').close(); $('#faqList').innerHTML = faqs.map(item => `<div class="faq-item"><button class="faq-q" aria-expanded="false">${item[0]}<span>+</span></button><div class="faq-a">${item[1]}</div></div>`).join(''); $('#faqList').querySelectorAll('.faq-item').forEach(item => { const question = item.querySelector('.faq-q'); Object.assign(question.style, { width: '100%', border: '0', background: 'transparent', color: 'var(--ink)', textAlign: 'left' }); question.onclick = () => { const open = item.classList.toggle('open'); question.setAttribute('aria-expanded', open); }; }); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }
function setupCommentSection() {
  const commentSection = `<section class="section testimonials" id="komentar"><div class="section-heading"><div><p class="eyebrow">Suara pelajar</p><h2>Berikan <em>komentar dan dukungan</em></h2><p class="muted">Komentar pada versi demo tersimpan di browser perangkat ini, belum dipublikasikan atau tersambung ke database.</p></div></div><div class="comment-layout"><form id="commentForm" class="testi"><label for="commentName">Nama (opsional)</label><input id="commentName" maxlength="40" placeholder="Tulis nama panggilan"><label for="commentType">Jenis pesan</label><select id="commentType"><option value="Komentar">Komentar</option><option value="Dukungan">Dukungan</option></select><label for="commentMessage">Pesan</label><textarea id="commentMessage" maxlength="500" required placeholder="Bagikan komentar atau dukunganmu…"></textarea><button class="btn" type="submit">Kirim pesan <span>→</span></button><p class="muted" id="commentStatus" aria-live="polite"></p></form><div class="testi-grid" id="commentList"></div></div></section>`;
  $('#faq').insertAdjacentHTML('beforebegin', commentSection);
  document.head.insertAdjacentHTML('beforeend', '<style>.comment-layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:20px}.comment-layout label{display:block;font-weight:600;font-size:12px;margin:0 0 6px}.comment-layout input,.comment-layout select,.comment-layout textarea{width:100%;border:1px solid var(--line);background:var(--paper);color:var(--ink);padding:11px;margin:0 0 15px}.comment-layout textarea{min-height:115px;resize:vertical}.comment-layout .testi-grid{grid-template-columns:repeat(2,1fr);align-content:start}@media(max-width:800px){.comment-layout{grid-template-columns:1fr}}@media(max-width:520px){.comment-layout .testi-grid{grid-template-columns:1fr}}</style>');
  const storageKey = 'madrasah-ilmu-demo-comments';
  const getComments = () => { try { return JSON.parse(localStorage.getItem(storageKey) || '[]'); } catch { return []; } };
  const renderComments = () => {
    const comments = getComments();
    if (!comments.length) {
      $('#commentList').innerHTML = '<article class="testi"><span>DEMO</span><p>Belum ada komentar yang tersimpan di perangkat ini.</p><div class="person"><i>—</i><div><b>Ruang komentar siap digunakan</b><small>Bagikan dukungan pertamamu</small></div></div></article>';
      return;
    }
    $('#commentList').innerHTML = comments.slice(0, 6).reverse().map(comment => {
      const name = escapeHtml(comment.name || 'Pengunjung');
      const initial = escapeHtml((comment.name || 'P').charAt(0).toUpperCase());
      return `<article class="testi"><span>${escapeHtml(comment.type)}</span><p>${escapeHtml(comment.message)}</p><div class="person"><i>${initial}</i><div><b>${name}</b><small>Disimpan di perangkat ini</small></div></div></article>`;
    }).join('');
  };
  renderComments();
  $('#commentForm').onsubmit = event => { event.preventDefault(); const name = $('#commentName').value.trim(); const type = $('#commentType').value; const message = $('#commentMessage').value.trim(); if (!message) return; try { const comments = getComments(); comments.push({ name, type, message }); localStorage.setItem(storageKey, JSON.stringify(comments.slice(-20))); $('#commentForm').reset(); $('#commentStatus').textContent = 'Pesan tersimpan di browser ini.'; renderComments(); } catch { $('#commentStatus').textContent = 'Pesan belum dapat disimpan di browser ini.'; } };
}
function setupCompetencyMenu() {
  $('#navlinks').insertAdjacentHTML('beforeend', '<button id="competencyMenuBtn" type="button">Uji Kompetensi</button>');
  document.body.insertAdjacentHTML('beforeend', '<dialog id="competencyModal"><button class="close-modal" id="closeCompetency" aria-label="Tutup">×</button><div class="quiz-head"><p class="eyebrow">UJI KOMPETENSI · DEMO</p><h2>Uji pemahamanmu</h2><div class="progress"><i id="competencyProgress" style="width:0"></i></div></div><div id="competencyContent"></div></dialog>');
  const menuButton = $('#competencyMenuBtn');
  Object.assign(menuButton.style, { border: '0', background: 'transparent', color: 'inherit', padding: '0', font: 'inherit', cursor: 'pointer' });
  menuButton.onclick = () => { $('#navlinks').classList.remove('open'); openCompetencyExam(); };
  $('#closeCompetency').onclick = () => $('#competencyModal').close();
  $('#competencyContent').style.padding = '28px';
}
init();
setupCompetencyMenu();
setupCommentSection();
['Dasar', 'Menengah', 'Lanjutan'].forEach(level => $('#levelFilter').insertAdjacentHTML('beforeend', `<option value="${level}">${level}</option>`));
// ============================================
// KODE INI DITAMBAHKAN KE PALING BAWAH file app.js
// (setelah semua kode yang sudah ada, sebelum baris renderCategories() dipanggil pertama kali)
// ============================================

const SUPABASE_URL = 'https://kgmqarcsqxodksfhkfgz.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnbXFhcmNzcXhvZGtzZmhrZmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3MjUyOTMsImV4cCI6MjEwMjMwMTI5M30.tl0-vqDrhddtXuOIk22qru_JrLHTTuODc-EJ-HFuyQw'; // ambil di Supabase > Project Settings > API > anon public key

async function loadFromSupabase() {
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/materi?select=*`, {
      headers: {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`
      }
    });
    const rows = await res.json();

    rows.forEach(row => {
      courses.push({
        title: row.title,
        cat: row.kategori,
        icon: row.icon || '✦',
        desc: row.deskripsi || '',
        level: row.level || 'Pemula',
        modules: row.modules || [],
        readings: row.readings || [],
        quiz: row.quiz || []
      });
    });

    renderCategories();
    renderCourses();
  } catch (err) {
    console.error('Gagal memuat data dari Supabase:', err);
  }
}

loadFromSupabase();
